// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: fulcrum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSoldiersServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sector string `protobuf:"bytes,2,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *GetSoldiersServiceReq) Reset() {
	*x = GetSoldiersServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSoldiersServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoldiersServiceReq) ProtoMessage() {}

func (x *GetSoldiersServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoldiersServiceReq.ProtoReflect.Descriptor instead.
func (*GetSoldiersServiceReq) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{0}
}

func (x *GetSoldiersServiceReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSoldiersServiceReq) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *GetSoldiersServiceReq) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type GetSoldiersServiceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Valor int64   `protobuf:"varint,2,opt,name=valor,proto3" json:"valor,omitempty"`
	Clock []int64 `protobuf:"varint,3,rep,packed,name=clock,proto3" json:"clock,omitempty"`
}

func (x *GetSoldiersServiceRes) Reset() {
	*x = GetSoldiersServiceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSoldiersServiceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoldiersServiceRes) ProtoMessage() {}

func (x *GetSoldiersServiceRes) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoldiersServiceRes.ProtoReflect.Descriptor instead.
func (*GetSoldiersServiceRes) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{1}
}

func (x *GetSoldiersServiceRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSoldiersServiceRes) GetValor() int64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *GetSoldiersServiceRes) GetClock() []int64 {
	if x != nil {
		return x.Clock
	}
	return nil
}

type GetServerServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetServerServiceReq) Reset() {
	*x = GetServerServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerServiceReq) ProtoMessage() {}

func (x *GetServerServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerServiceReq.ProtoReflect.Descriptor instead.
func (*GetServerServiceReq) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{2}
}

func (x *GetServerServiceReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetServerServiceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetServerServiceRes) Reset() {
	*x = GetServerServiceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerServiceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerServiceRes) ProtoMessage() {}

func (x *GetServerServiceRes) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerServiceRes.ProtoReflect.Descriptor instead.
func (*GetServerServiceRes) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerServiceRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddBaseServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sector string `protobuf:"bytes,2,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	Valor  *int64 `protobuf:"varint,4,opt,name=valor,proto3,oneof" json:"valor,omitempty"`
}

func (x *AddBaseServiceReq) Reset() {
	*x = AddBaseServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBaseServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBaseServiceReq) ProtoMessage() {}

func (x *AddBaseServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBaseServiceReq.ProtoReflect.Descriptor instead.
func (*AddBaseServiceReq) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{4}
}

func (x *AddBaseServiceReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddBaseServiceReq) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *AddBaseServiceReq) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *AddBaseServiceReq) GetValor() int64 {
	if x != nil && x.Valor != nil {
		return *x.Valor
	}
	return 0
}

type RenameBaseServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sector string `protobuf:"bytes,2,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	Name   string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RenameBaseServiceReq) Reset() {
	*x = RenameBaseServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameBaseServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameBaseServiceReq) ProtoMessage() {}

func (x *RenameBaseServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameBaseServiceReq.ProtoReflect.Descriptor instead.
func (*RenameBaseServiceReq) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{5}
}

func (x *RenameBaseServiceReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenameBaseServiceReq) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *RenameBaseServiceReq) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *RenameBaseServiceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateValueServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sector string `protobuf:"bytes,2,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	Valor  int64  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
}

func (x *UpdateValueServiceReq) Reset() {
	*x = UpdateValueServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateValueServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateValueServiceReq) ProtoMessage() {}

func (x *UpdateValueServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateValueServiceReq.ProtoReflect.Descriptor instead.
func (*UpdateValueServiceReq) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateValueServiceReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateValueServiceReq) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *UpdateValueServiceReq) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *UpdateValueServiceReq) GetValor() int64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

type DeleteBaseServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sector string `protobuf:"bytes,2,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *DeleteBaseServiceReq) Reset() {
	*x = DeleteBaseServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBaseServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBaseServiceReq) ProtoMessage() {}

func (x *DeleteBaseServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBaseServiceReq.ProtoReflect.Descriptor instead.
func (*DeleteBaseServiceReq) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBaseServiceReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteBaseServiceReq) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *DeleteBaseServiceReq) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type ConnectServiceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Clock []int64 `protobuf:"varint,2,rep,packed,name=clock,proto3" json:"clock,omitempty"`
}

func (x *ConnectServiceRes) Reset() {
	*x = ConnectServiceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectServiceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectServiceRes) ProtoMessage() {}

func (x *ConnectServiceRes) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectServiceRes.ProtoReflect.Descriptor instead.
func (*ConnectServiceRes) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectServiceRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectServiceRes) GetClock() []int64 {
	if x != nil {
		return x.Clock
	}
	return nil
}

type AskServerServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sector string `protobuf:"bytes,2,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *AskServerServiceReq) Reset() {
	*x = AskServerServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskServerServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskServerServiceReq) ProtoMessage() {}

func (x *AskServerServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskServerServiceReq.ProtoReflect.Descriptor instead.
func (*AskServerServiceReq) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{9}
}

func (x *AskServerServiceReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AskServerServiceReq) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *AskServerServiceReq) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type AskServerServiceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Valor int64  `protobuf:"varint,2,opt,name=valor,proto3" json:"valor,omitempty"`
}

func (x *AskServerServiceRes) Reset() {
	*x = AskServerServiceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskServerServiceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskServerServiceRes) ProtoMessage() {}

func (x *AskServerServiceRes) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskServerServiceRes.ProtoReflect.Descriptor instead.
func (*AskServerServiceRes) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{10}
}

func (x *AskServerServiceRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AskServerServiceRes) GetValor() int64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

var File_fulcrum_proto protoreflect.FileDescriptor

var file_fulcrum_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x53, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6c, 0x64, 0x69, 0x65, 0x72, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x22, 0x53, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6c, 0x64, 0x69,
	0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x74, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x42, 0x61,
	0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x66, 0x0a,
	0x14, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x69, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72,
	0x22, 0x52, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f,
	0x63, 0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x22,
	0x51, 0x0a, 0x13, 0x41, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x22, 0x3b, 0x0a, 0x13, 0x41, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x32,
	0x8b, 0x01, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6c, 0x64, 0x69, 0x65, 0x72, 0x73,
	0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6c, 0x64, 0x69, 0x65, 0x72, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f,
	0x6c, 0x64, 0x69, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x39, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x14, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x32, 0xf9, 0x01,
	0x0a, 0x0f, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x33, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x42, 0x61, 0x73, 0x65, 0x12, 0x12, 0x2e, 0x41,
	0x64, 0x64, 0x42, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x42, 0x61, 0x73, 0x65, 0x12, 0x15, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x3b, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x16, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x39,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x15, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x32, 0x4c, 0x0a, 0x0f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x64, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x09,
	0x41, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x41, 0x73, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x14, 0x2e, 0x41, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fulcrum_proto_rawDescOnce sync.Once
	file_fulcrum_proto_rawDescData = file_fulcrum_proto_rawDesc
)

func file_fulcrum_proto_rawDescGZIP() []byte {
	file_fulcrum_proto_rawDescOnce.Do(func() {
		file_fulcrum_proto_rawDescData = protoimpl.X.CompressGZIP(file_fulcrum_proto_rawDescData)
	})
	return file_fulcrum_proto_rawDescData
}

var file_fulcrum_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_fulcrum_proto_goTypes = []interface{}{
	(*GetSoldiersServiceReq)(nil), // 0: GetSoldiersServiceReq
	(*GetSoldiersServiceRes)(nil), // 1: GetSoldiersServiceRes
	(*GetServerServiceReq)(nil),   // 2: GetServerServiceReq
	(*GetServerServiceRes)(nil),   // 3: GetServerServiceRes
	(*AddBaseServiceReq)(nil),     // 4: AddBaseServiceReq
	(*RenameBaseServiceReq)(nil),  // 5: RenameBaseServiceReq
	(*UpdateValueServiceReq)(nil), // 6: UpdateValueServiceReq
	(*DeleteBaseServiceReq)(nil),  // 7: DeleteBaseServiceReq
	(*ConnectServiceRes)(nil),     // 8: ConnectServiceRes
	(*AskServerServiceReq)(nil),   // 9: AskServerServiceReq
	(*AskServerServiceRes)(nil),   // 10: AskServerServiceRes
}
var file_fulcrum_proto_depIdxs = []int32{
	0,  // 0: BrokerService.GetSoldiers:input_type -> GetSoldiersServiceReq
	2,  // 1: BrokerService.GetServer:input_type -> GetServerServiceReq
	4,  // 2: InformerService.AddBase:input_type -> AddBaseServiceReq
	5,  // 3: InformerService.RenameBase:input_type -> RenameBaseServiceReq
	6,  // 4: InformerService.UpdateValue:input_type -> UpdateValueServiceReq
	7,  // 5: InformerService.DeleteBase:input_type -> DeleteBaseServiceReq
	9,  // 6: ServidorService.AskServer:input_type -> AskServerServiceReq
	1,  // 7: BrokerService.GetSoldiers:output_type -> GetSoldiersServiceRes
	3,  // 8: BrokerService.GetServer:output_type -> GetServerServiceRes
	8,  // 9: InformerService.AddBase:output_type -> ConnectServiceRes
	8,  // 10: InformerService.RenameBase:output_type -> ConnectServiceRes
	8,  // 11: InformerService.UpdateValue:output_type -> ConnectServiceRes
	8,  // 12: InformerService.DeleteBase:output_type -> ConnectServiceRes
	10, // 13: ServidorService.AskServer:output_type -> AskServerServiceRes
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_fulcrum_proto_init() }
func file_fulcrum_proto_init() {
	if File_fulcrum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fulcrum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSoldiersServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSoldiersServiceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerServiceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBaseServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameBaseServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateValueServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBaseServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectServiceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskServerServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskServerServiceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_fulcrum_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fulcrum_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_fulcrum_proto_goTypes,
		DependencyIndexes: file_fulcrum_proto_depIdxs,
		MessageInfos:      file_fulcrum_proto_msgTypes,
	}.Build()
	File_fulcrum_proto = out.File
	file_fulcrum_proto_rawDesc = nil
	file_fulcrum_proto_goTypes = nil
	file_fulcrum_proto_depIdxs = nil
}
